#version: "3"
services:
  fastapi:
    build: .
    environment:
      - DB_HOST=db
      - DB_PASS=admin
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
#    ports:
#      - 80:8000
    command:  sh -c "sleep 10 && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
#    command:  sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
#      - ./migrations:/app/migrations
#      - mediafiles:/app/media
    networks:
      - webnet

  db:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
#    ports:
#      - 5432:5432
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
#      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - './static:/app/static'
    depends_on:
      - fastapi
    networks:
      - webnet

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - webnet


  celery_worker:
      build: .
      container_name: celery_worker
      mem_limit: 2g
      command: celery -A tasks worker --loglevel=INFO
      volumes:
        - .:/app
      depends_on:
        - redis
        - fastapi
      environment:
        - DB_HOST=db
        - DB_PASS=admin
        - DB_PORT=5432
        - DB_USER=postgres
        - DB_NAME=postgres
        - REDIS_URL=redis://redis:6379/0
      networks:
        - webnet

networks:
  webnet:
#
volumes:
  pgdata:
#  mediafiles:

